#!/usr/bin/env python2

from flask import Flask
import caldav
import scheduler_adapter


app = Flask(__name__)


@app.route('/events')
def getAllEvents():
    url = 'http://test:test@localhost:8080/test/Calendar.ics/'
    client = caldav.DAVClient(url)
    cal = caldav.Calendar(client, '/test/calendar.ics/')
    scheduler_adapter.schedulerDataFromCal(cal)

if __name__ == '__main__':
    app.run()
